# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - 'rewrite/main'
  paths:
    include:
    - src/*
    exclude:
    - src/Quarrel/Strings/*
    - src/Quarrel/MultilingualResources/*
    - src/Quarrel/Assets/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Debug'
  # buildPlatform: 'x86|x64|ARM|ARM64'
  # buildConfiguration: 'Alpha'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  buildDir: '$(build.artifactStagingDirectory)\build\\'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: 'x86'
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/p:AppxBundlePlatforms="$(buildPlatform)"
                  /p:AppxPackageDir="$(appxPackageDir)"
                  /p:OutputPath="$(buildDir)"
                  /p:AppxBundle=Always
                  /p:UapAppxPackageBuildMode=StoreUpload
                  /t:Quarrel'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactStagingDirectory)'
  inputs:
    SourceFolder: '$(appxPackageDir)'
    Contents: '**'
    TargetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'Avid29'
    repositoryName: 'UWPCommunity/Quarrel'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tag: "Alpha"
    tagSource: 'gitTag'
    title: '$(Build.BuildNumber)'
    isPreRelease: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
